@baseUrl=http://localhost:3800
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzNDYzYjk5YjYyYTcyZjI2ZWQ2NzdjYzU1NmM0NGU4IiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkR1h5aU1HcFFsUlJGcWExcmluUHEuZXRjM3pKUWE2NEhhMndkZVM2SUJrTnpWYzUvS2Q4Q1MiLCJpYXQiOjE3MjU4NTczMzAsImV4cCI6MTcyNTg1NzkzMH0.N-DdY2ZDxXpT533QS8szHtPT0vzDPmfDVQwpfFx4av0

###
GET {{baseUrl}}
Accept: application/json
Origin: {{baseUrl}}

###
POST {{baseUrl}}/token
Content-Type: application/json
Accept: application/json
Origin: {{baseUrl}}

{
    "id": "23463b99b62a72f26ed677cc556c44e8",
    "email": "example@example.com",
    "password": "example@example.com"   
}

###
POST {{baseUrl}}/protegido
Content-Type: application/json
Accept: application/json
Origin: {{baseUrl}}
Authorization: Bearer {{token}}

{
    "email": "example@example.com",
    "password": "example@example.com"   
}