@originHeaders=http://localhost:3099
@baseUrl=/api/v1/auth

### 
# @name register
# Registrar un nuevo usuario
POST {{originHeaders}}{{baseUrl}}/register
Content-Type: application/json
Accept: application/json
Origin: {{originHeaders}}

{
    "name": "User Demo",
    "email": "user.demo@example.com",
    "password": "user.demo@example.com"
}

### 
# @name sign_in
# Iniciar sesión al sistema
POST {{originHeaders}}{{baseUrl}}/sign_in
Content-Type: application/json
Accept: application/json
Origin: {{originHeaders}}

{
    "email": "user.demo@example.com",
    "password": "user.demo@example.com"
}