@originHeaders=http://localhost:3099
@baseUrl=/api/v1/main
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGY1NThiZmEwMGExZTc1Y2FhYmRhMCIsImVtYWlsIjoidXNlci5kZW1vQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI1OTE2MTA4LCJleHAiOjE3MjU5MTY3MDh9.UGlokVAd1oRZAI4PHZBu5rlIrKHx1TNl1SjwTbRjjUU

### 
# @name mainPublico
# Probar ruta público
GET {{originHeaders}}{{baseUrl}}/publico
Content-Type: application/json
Accept: application/json
Origin: {{originHeaders}}

{
    "name": "User Demo",
    "email": "user.demo@example.com",
    "password": "user.demo@example.com"
}

### 
# @name mainPrivado
# Probar ruta privado
GET {{originHeaders}}{{baseUrl}}/privado
Content-Type: application/json
Accept: application/json
Origin: {{originHeaders}}
Authorization: Bearer {{token}}

{
    "name": "User Demo",
    "email": "user.demo@example.com",
    "password": "user.demo@example.com"
}
